data = [
    {'name': 'Instagram',
     'followers_count': 648,
     'description': 'Social media platform',
     'country': 'United States'},
    {'name': 'Christiano Ronaldo',
     'followers_count': 597,
     'description': 'Footballer',
     'country': 'Portugal'},
    {'name': 'Lionel Messi',
     'followers_count': 481,
     'description': 'Footballer',
     'country': 'Argentina'},
    {'name': 'Selena Gomez',
     'followers_count': 426,
     'description': 'Musician,Actress and businesswoman',
     'country': 'United States'},
    {'name': 'Kylie Jenner',
     'followers_count': 397,
     'description': 'Television personality and businnesswoman',
     'country': 'United States'},
    {'name': 'Dwayne Johnson',
     'followers_count': 388,
     'description': 'Actor and professional wrestler',
     'country': 'United States'},
    {'name': 'Ariana Grande',
     'followers_count': 377,
     'description': 'Musician,actress and businesswoman',
     'country': 'United States'},
    {'name': 'Kim Kardashian',
     'followers_count': 363,
     'description': 'Television personality, model and businesswoman',
     'country': 'United States'},
    {'name': 'Beyonce',
     'followers_count': 315,
     'description': 'Musician and businesswoman',
     'country': 'United States'},
    {'name': 'Kloe Kardashian',
     'followers_count': 311,
     'description': 'Television personality and businesswoman',
     'country': 'United States'},
    {'name': 'Nike',
     'followers_count': 302,
     'description': 'Sportswear multinational',
     'country': 'United States'},
    {'name': 'Justin Bieber',
     'followers_count': 293,
     'description': 'Musician',
     'country': 'Canada'},
    {'name': 'Kendall Jenner',
     'followers_count': 293,
     'description': 'Model and television personality',
     'country': 'United States'},
    {'name': 'National Geographic',
     'followers_count': 281,
     'description': 'Magazine',
     'country': 'United States'},
    {'name': 'Tylor Swift',
     'followers_count': 269,
     'description': 'Musician',
     'country': 'United States'},
    {'name': 'Virat Kohli',
     'followers_count': 255,
     'description': 'Cricketer',
     'country': 'India'},
    {'name': 'Jennifer Lopez',
     'followers_count': 249,
     'description': 'Musician and actress',
     'country': 'United States'},
    {'name': 'Nicki Minaj',
     'followers_count': 224,
     'description': 'Musician',
     'country': 'United States'},
    {'name': 'Kourtney Kardashian',
     'followers_count': 224,
     'description': 'Television personality and model',
     'country': 'United States'},
    {'name': 'Miley Cyrus',
     'followers_count': 212,
     'description': 'Musician and actress',
     'country': 'United States'},
    {'name': 'Neymar',
     'followers_count': 210,
     'description': 'Footballer',
     'country': 'Brazil'},
    {'name': 'Katy Perry',
     'followers_count': 203,
     'description': 'Musician and businesswoman',
     'country': 'United States'},
    {'name': 'Zendaya',
     'followers_count': 183,
     'description': 'Actress and singer',
     'country': 'United States'},
    {'name': 'Kevin Hart',
     'followers_count': 178,
     'description': 'Comedian and actor',
     'country': 'United States'},
    {'name': 'Cardi B',
     'followers_count': 168,
     'description': 'Musician and Actress',
     'country': 'United States'},
    {'name': 'Lebron James',
     'followers_count': 157,
     'description': 'Basketball Player',
     'country': 'United States'},
    {'name': 'Demi Lovato',
     'followers_count': 157,
     'description': 'Musician and Actress',
     'country': 'United States'},
    {'name': 'Rihanna',
     'followers_count': 152,
     'description': 'Musician and businesswoman',
     'country': 'Barbados'},
    {'name': 'Real madrid',
     'followers_count': 144,
     'description': 'Football Club',
     'country': 'Spain'},
    {'name': 'Chris Brown',
     'followers_count': 142,
     'description': 'Musician',
     'country': 'United States'},
    {'name': 'Drake',
     'followers_count': 141,
     'description': 'Musician',
     'country': 'Canada'},
    {'name': 'Ellen DeGeneres',
     'followers_count': 139,
     'description': 'Comedian and television personality',
     'country': 'United States'},
    {'name': 'FC Barcelona',
     'followers_count': 122,
     'description': 'Football club',
     'country': 'Spain'},
    {'name': 'Billie Eilish',
     'followers_count': 109,
     'description': 'Musician',
     'country': 'United States'},
    {'name': 'UEFA Champions League',
     'followers_count': 107,
     'description': 'Club Football Competition',
     'country': 'Europe'},
    {'name': 'Gal Gadot',
     'followers_count': 106,
     'description': 'Actress',
     'country': 'Israel'},
    {'name': 'Kylian Mbappe',
     'followers_count': 106,
     'description': 'Footballer',
     'country': 'France'},
    {'name': 'Vin Diesel',
     'followers_count': 98,
     'description': 'Actor',
     'country': 'United States'},
    {'name': 'Lisa',
     'followers_count': 96,
     'description': 'Musician',
     'country': 'Thailand'},
    {'name': 'Nasa',
     'followers_count': 94,
     'description': 'Space agency',
     'country': 'United States'},
    {'name': 'Dua Lipa',
     'followers_count': 89,
     'description': 'Musician',
     'country': 'United Kingdom'},
    {'name': 'Priyanka Chopra',
     'followers_count': 89,
     'description': 'Actress',
     'country': 'India'},
    {'name': 'Shakira',
     'followers_count': 88,
     'description': 'Musician',
     'country': 'Colombia'},
    {'name': 'NBA',
     'followers_count': 83,
     'description': 'Professional basketball league',
     'country': 'United States'},
    {'name': 'Shraddha Kapoor ',
     'followers_count': 82,
     'description': 'Actress',
     'country': 'India'},
    {'name': 'David Beckham',
     'followers_count': 81,
     'description': 'Football Coach',
     'country': 'United Kingdom'},
    {'name': 'Snoop Dogg',
     'followers_count': 80,
     'description': 'Musician',
     'country': 'United States'},
    {'name': 'Jennie',
     'followers_count': 80,
     'description': 'Musician',
     'country': 'South Korea'},
    {'name': 'Khaby Lame',
     'followers_count': 80,
     'description': 'Social media personality',
     'country': 'Italy'},
    {'name': 'Gigi Hadid',
     'followers_count': 79,
     'description': 'Model',
     'country': 'United States'},
]